# Generated by Django 5.2 on 2025-04-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_cleaner_property_cleaningrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('homeowner', 'Homeowner'), ('cleaner', 'Cleaner')], max_length=20),
        ),
    ]
