# Generated by Django 5.2 on 2025-04-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeowner',
            name='favourite_cleaners',
            field=models.ManyToManyField(blank=True, related_name='favourite_homeowners', to='webapp.cleaner'),
        ),
    ]
