# Generated by Django 5.2 on 2025-04-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_homeowner_favourite_cleaners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeowner',
            name='favourite_cleaners',
            field=models.ManyToManyField(blank=True, related_name='favourite_cleaners', to='webapp.cleaner'),
        ),
    ]
