# Generated by Django 5.2 on 2025-04-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_homeowner_favourite_cleaners'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
