# Generated by Django 5.2 on 2025-04-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_servicecategory_cleaninglisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaninglisting',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
