# Generated by Django 5.2 on 2025-04-29 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_cleaninglisting_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaninglisting',
            name='views',
        ),
    ]
