# Generated by Django 5.2 on 2025-04-29 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_remove_cleaninglisting_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform_Manager',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.userprofile')),
            ],
            bases=('webapp.userprofile',),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('homeowner', 'Homeowner'), ('cleaner', 'Cleaner'), ('platform_manager', 'Platform Manager')], max_length=50),
        ),
    ]
