# Generated by Django 5.2 on 2025-04-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_platform_manager_servicecategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('homeowner', 'Homeowner'), ('cleaner', 'Cleaner'), ('platform manager', 'Platform Manager')], max_length=50),
        ),
    ]
