# Generated by Django 5.2 on 2025-04-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_cleaninglisting_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Platform_Manager',
            new_name='PlatformManager',
        ),
    ]
