# Generated by Django 5.2 on 2025-05-01 04:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_rename_platform_manager_platformmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaner',
            name='cleaning_requests',
        ),
        migrations.RemoveField(
            model_name='cleaninglisting',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='cleaninglisting',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='cleaninglisting',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='cleaningrequest',
            name='cleaner',
        ),
        migrations.RemoveField(
            model_name='cleaningrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_address',
        ),
        migrations.AddField(
            model_name='cleaner',
            name='cleaning_listings',
            field=models.ManyToManyField(blank=True, related_name='cleaners', to='webapp.cleaninglisting'),
        ),
        migrations.AddField(
            model_name='cleaninglisting',
            name='date_closed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cleaninglisting',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cleaninglisting',
            name='requests',
            field=models.ManyToManyField(blank=True, related_name='cleaning_listings', to='webapp.cleaningrequest'),
        ),
        migrations.AddField(
            model_name='homeowner',
            name='favourite_listings',
            field=models.ManyToManyField(blank=True, related_name='favourite_listings', to='webapp.cleaninglisting'),
        ),
        migrations.AlterField(
            model_name='cleaninglisting',
            name='service_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.servicecategory'),
        ),
        migrations.AlterField(
            model_name='cleaninglisting',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='cleaningrequest',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.property'),
        ),
        migrations.AlterField(
            model_name='cleaningrequest',
            name='status',
            field=models.CharField(choices=[('pending_cleaner_accept', 'Pending Cleaner Accept'), ('pending_cleaning', 'Pending Cleaning'), ('pending_review', 'Pending Review'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending_cleaner_accept', max_length=40),
        ),
    ]
