# Generated by Django 5.2 on 2025-05-01 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_remove_cleaner_cleaning_requests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaner',
            name='cleaning_listings',
        ),
        migrations.AddField(
            model_name='cleaninglisting',
            name='cleaner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.cleaner'),
        ),
        migrations.AddField(
            model_name='cleaningrequest',
            name='cleaning_listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.cleaninglisting'),
        ),
    ]
