# Generated by Django 5.2 on 2025-05-01 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_remove_cleaner_cleaning_listings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property_type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='homeowner',
            name='properties',
        ),
        migrations.AddField(
            model_name='property',
            name='homeowner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.homeowner'),
        ),
    ]
