# Generated by Django 5.2 on 2025-05-01 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_rename_property_type_property_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaninglisting',
            name='requests',
        ),
    ]
