# Generated by Django 5.2 on 2025-05-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_cleaninglisting_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningrequest',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cleaningrequest',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
