# Generated by Django 5.2 on 2025-05-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_cleaningrequest_feedback_cleaningrequest_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningrequest',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cleaningrequest',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
