# Generated by Django 5.2 on 2025-05-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_alter_cleaningrequest_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaninglisting',
            name='rating',
            field=models.FloatField(default=None, null=True),
        ),
    ]
