# Generated by Django 5.2 on 2025-05-04 04:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_cleaninglisting_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaninglisting',
            name='views',
        ),
        migrations.CreateModel(
            name='CleaningListingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_viewed', models.DateTimeField(default=django.utils.timezone.now)),
                ('cleaning_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.cleaninglisting')),
                ('homeowner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.homeowner')),
            ],
        ),
    ]
