# Generated by Django 5.2 on 2025-05-04 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_remove_cleaninglisting_views_cleaninglistingview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaninglistingview',
            name='homeowner',
        ),
        migrations.AddField(
            model_name='cleaninglistingview',
            name='viewing_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.userprofile'),
        ),
    ]
