# Generated by Django 5.2 on 2025-05-04 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_remove_cleaninglistingview_homeowner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaninglistingview',
            name='viewing_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.homeowner'),
        ),
    ]
