# Generated by Django 5.2 on 2025-05-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_alter_cleaninglistingview_viewing_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaninglistingview',
            old_name='viewing_user',
            new_name='homeowner',
        ),
    ]
